### ISSUE TITLE
Project Requirements

### ISSUE THREAD

**Issue by Zeragamba** [step1041/Athena#1]
Determine what are Project Athena's requirements. When we've figured out all the requirements, we can turn these into Issues, and add them to the project boards

MVP
- [ ] Record Rank - (#9)
- [ ] Record Win/Loss/Draw - (#9)
- [ ] Save to database (backend working) - (#9)
- [ ] Web accessible - (#9, #10)

v1 - Multi-User
- [ ] User login - (#12)
- [ ] Blizzard.net OAuth login - (#12)
- [ ] Allow shareable URLs

v2 - Basic Stats
- [ ] Win/Loss Streak - (#11)
- [ ] SR Velocity
- [ ] Record Map
- [ ] Record group size
- [ ] Record match notes 

v3 - Hero and map stats
- [ ] Record heros played
- [ ] Display win % per hero
- [ ] Record map played
- [ ] Display win % per map

**Comment by Avendor7** [comment]
**Project Notes**

Things to consider 
1. Pagination on table?
2. Modal or inline editing?
3. Colour scheme?
4. Easter Eggs something something Konami code


For future table sorting:
http://www.jarrodctaylor.com/posts/Filter-And-Sort-Tables-In-Ember/ 

Current database items
- id
- createdAt
- updatedAt
- rank
- outcome

Future database items to be added
- game number
- map
- group size
- heroes
- notes
